import type { Unite } from './schema'

export const unites: Unite[] = [
  {
    numero: 0,
    titre: 'Comprendre le corps qui danse',
    description: "Les fondamentaux communs à toutes les disciplines : mouvement selon Laban, anatomie appliquée, formation musicale et repères d'espace scénique.",
    coursIds: ['laban-mouvement', 'anatomie-danseur', 'musique-appliquee', 'espace-scenique'],
    termeIds: [
      'effort-laban', 'kinesphere', 'niveaux-espace', 'qualites-de-mouvement',
      'alignement', 'turn-out', 'centre-de-gravite', 'tonicite', 'proprioception',
      'tempo', 'mesure-musicale', 'phrase-musicale', 'anacrouse', 'syncope',
      'cote-cour', 'cote-jardin', 'face-lointain', 'diagonale', 'en-croix',
    ],
    quizDisponibles: ['qcm', 'texte-a-trous'],
    iconeSvgId: 'corps-qui-danse',
  },
  {
    numero: 1,
    titre: 'Histoire et évolution des arts chorégraphiques',
    description: 'De la naissance du ballet de cour aux disciplines contemporaines : histoire des huit disciplines, frise chronologique et schéma des origines et interactions.',
    coursIds: ['histoire-ballet', 'histoire-moderne-contemporain', 'histoire-jazz', 'histoire-cabaret-burlesque-heels', 'histoire-pole-dance'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association'],
    iconeSvgId: 'histoire-danse',
  },
  {
    numero: 2,
    titre: 'Classique',
    description: 'Positions des pieds et des bras, barre et milieu, adage, allegro, tours, batterie et liaisons — le vocabulaire académique de la danse classique.',
    coursIds: ['intro-classique'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous'],
    iconeSvgId: 'classique',
  },
  {
    numero: 3,
    titre: 'Contemporain',
    description: 'Travail au sol, release, poids et abandon, spirales, contact improvisation — le vocabulaire de la danse contemporaine et ses concepts clés.',
    coursIds: ['intro-contemporain'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous'],
    iconeSvgId: 'contemporain',
  },
  {
    numero: 4,
    titre: 'Moderne',
    description: 'Héritage générique de la danse moderne : contraction et release, fall and recovery, isolations, travail du buste et du bassin.',
    coursIds: ['intro-moderne'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous'],
    iconeSvgId: 'moderne',
  },
  {
    numero: 5,
    titre: 'Jazz et sous-styles',
    description: 'Tronc commun jazz et sept sous-styles différenciés : jazz classique, Broadway, Fosse, modern jazz, lyrical, street jazz et afro-jazz.',
    coursIds: ['intro-jazz', 'sous-styles-jazz'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous'],
    iconeSvgId: 'jazz',
  },
  {
    numero: 6,
    titre: 'Heels',
    description: 'Danse sur talons hauts : posture, walks, mouvements signature, floorwork, présence et filiations culturelles.',
    coursIds: ['intro-heels'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous'],
    iconeSvgId: 'heels',
  },
  {
    numero: 7,
    titre: 'Cabaret',
    description: 'Esthétiques scéniques, french cancan, revue et music-hall, port du costume et des accessoires, lignes de chorus.',
    coursIds: ['intro-cabaret'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous'],
    iconeSvgId: 'cabaret',
  },
  {
    numero: 8,
    titre: 'Pole dance',
    description: "Pole sport, pole art, exotic et pole theatre : prises, montées, figures, inversions, floorwork — et l'histoire de celles qui ont créé cette discipline.",
    coursIds: ['intro-pole-dance', 'histoire-culturelle-pole'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous'],
    iconeSvgId: 'pole-dance',
  },
  {
    numero: 9,
    titre: 'Effeuillage burlesque',
    description: 'Art du dévoilement progressif, jeu de scène, personnage et rapport au public : le vocabulaire du burlesque artistique.',
    coursIds: ['intro-burlesque'],
    termeIds: [],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous'],
    iconeSvgId: 'burlesque',
  },
  {
    numero: 10,
    titre: 'Danser sans se blesser',
    description: 'Prévention fondée sur la science : épidémiologie, facteurs de risque, renforcement neuromusculaire et spécificités par discipline.',
    coursIds: ['prevention-generale', 'prevention-par-discipline'],
    termeIds: [],
    quizDisponibles: ['qcm', 'texte-a-trous'],
    iconeSvgId: 'sante',
  },
  {
    numero: 11,
    titre: "L'art de l'improvisation et la composition",
    description: 'Improvisation comme outil de création, composition chorégraphique et une fiche culturelle sur les systèmes de notation de la danse.',
    coursIds: ['improvisation', 'composition', 'notation-danse'],
    termeIds: [],
    quizDisponibles: ['qcm', 'texte-a-trous'],
    iconeSvgId: 'improvisation',
  },
]
