import type { Unite } from './schema'

export const unites: Unite[] = [
  {
    numero: 1,
    titre: 'Comprendre le corps qui danse',
    description: "Les fondamentaux communs à toutes les disciplines : mouvement selon Laban (six cours dédiés), anatomie appliquée et repères d'espace scénique.",
    coursIds: ['laban-introduction', 'laban-effort-poids', 'laban-effort-espace', 'laban-effort-temps', 'laban-effort-flux', 'laban-synthese', 'anatomie-danseur', 'espace-scenique'],
    termeIds: [
      'effort-laban', 'kinesphere', 'niveaux-espace', 'qualites-de-mouvement',
      'alignement', 'turn-out', 'centre-de-gravite', 'tonicite', 'proprioception',
      'cote-cour', 'cote-jardin', 'face-lointain', 'diagonale', 'en-croix',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'corps-qui-danse',
  },
  {
    numero: 2,
    titre: 'Histoire et évolution des arts chorégraphiques',
    description: 'De la naissance du ballet de cour aux disciplines contemporaines : histoire des huit disciplines, frise chronologique et schéma des origines et interactions.',
    coursIds: ['histoire-ballet', 'histoire-moderne-contemporain', 'histoire-jazz', 'histoire-cabaret-burlesque-heels', 'histoire-pole-dance'],
    termeIds: [
      'ballet-de-cour', 'ballet-romantique', 'ballet-classique-academique', 'sur-les-pointes', 'corps-de-ballet',
      'danse-moderne', 'ausdruckstanz', 'danse-contemporaine', 'danse-postmoderne', 'contact-improvisation',
      'origines-jazz-dance', 'lindy-hop', 'jazz-theatrical',
      'cotton-club', 'katherine-dunham', 'alvin-ailey', 'nicholas-brothers', 'matt-mattox',
      'cancan', 'kabarett',
      'burlesque-origines', 'neo-burlesque',
      'vogue-ballroom', 'heels-dance',
      'mat-chinois', 'pole-contemporain',
    ],
    quizDisponibles: ['qcm', 'association', 'flashcards'],
    iconeSvgId: 'histoire-danse',
  },
  {
    numero: 3,
    titre: 'Formation musicale pour le danseur',
    description: "Tempo, mesure, phrasé, marquages italiens, dynamiques, articulation et formes musicales — tout ce qu'un danseur doit entendre pour dialoguer avec la musique plutôt que la suivre.",
    coursIds: ['musique-appliquee', 'marquages-tempo', 'dynamiques-musicales', 'formes-musicales'],
    termeIds: [
      'tempo', 'mesure-musicale', 'phrase-musicale', 'anacrouse', 'syncope',
      'marquage-tempo', 'rubato',
      'dynamiques-musicales', 'crescendo', 'legato', 'staccato',
      'forme-musicale', 'motif-musical', 'cadence-harmonique',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'musique',
  },
  {
    numero: 4,
    titre: 'Classique',
    description: 'Positions des pieds et des bras, barre et milieu, adage, allegro, tours, batterie et liaisons — le vocabulaire académique de la danse classique.',
    coursIds: ['intro-classique'],
    termeIds: [
      'barre-classique', 'milieu-classique', 'en-dehors-en-dedans',
      'cinq-positions-pieds', 'positions-bras', 'epaulement',
      'plie', 'releve', 'tendu', 'degage', 'rond-de-jambe', 'fondu', 'frappe', 'developpe', 'grand-battement',
      'port-de-bras', 'adage', 'arabesque', 'attitude',
      'allegro', 'echappe', 'assemble', 'jete', 'pas-de-chat', 'glissade',
      'grand-jete', 'pas-de-deux', 'sissonne', 'changement-de-pied', 'temps-leve',
      'demi-pointes', 'ballon', 'coupe', 'enchainement', 'etoile',
      'pirouette', 'fouette', 'chaines',
      'batterie', 'pas-de-bourree',
    ],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'classique',
  },
  {
    numero: 5,
    titre: 'Contemporain',
    description: 'Travail au sol, release, poids et abandon, spirales, contact improvisation — le vocabulaire de la danse contemporaine et ses concepts clés.',
    coursIds: ['intro-contemporain'],
    termeIds: [
      'release-technique', 'poids-abandon', 'gravite-contemporain',
      'contraction-release', 'fall-recovery',
      'suspension', 'rebond-swing', 'fluidite-mouvement', 'discontinuite', 'vibration',
      'spirale', 'torsion', 'desequilibre',
      'floorwork', 'roulade', 'chute-controlee',
      'point-de-contact', 'partage-poids',
      'phrase-mouvement', 'score-improvisation', 'instant-composition',
      'somatique', 'body-mind-centering', 'feldenkrais', 'site-specific',
    ],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'contemporain',
  },
  {
    numero: 6,
    titre: 'Moderne',
    description: 'Héritage générique de la danse moderne : contraction et release, fall and recovery, isolations, travail du buste et du bassin.',
    coursIds: ['intro-moderne'],
    termeIds: [
      'isolation', 'succession-corporelle', 'opposition-corps',
      'flat-back', 'hinge', 'undulation', 'table-moderne', 'lunge-moderne',
      'travail-bassin', 'polycentrisme',
      'technique-horton', 'technique-cunningham', 'technique-limon',
      'canon', 'unisson', 'marche-moderne', 'elevation-moderne',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'moderne',
  },
  {
    numero: 7,
    titre: 'Jazz et sous-styles',
    description: 'Tronc commun jazz et sept sous-styles différenciés : jazz classique, Broadway, Fosse, modern jazz, lyrical, street jazz et afro-jazz.',
    coursIds: ['intro-jazz', 'sous-styles-jazz'],
    termeIds: [
      'groove', 'accent-jazz', 'eight-count', 'preparation-elan',
      'ball-change', 'jazz-square', 'chasse-jazz', 'jazz-walk',
      'arm-styling', 'niveau-bas', 'pirouette-jazz', 'leaps-jazz', 'isolations-jazz',
      'jazz-run', 'kick-jazz', 'hip-roll', 'freeze-jazz', 'barrel-turn',
      'stag-leap', 'tilt-jazz', 'pivot-turn', 'moonwalk',
      'sous-style-jazz-classique', 'sous-style-broadway', 'sous-style-fosse',
      'sous-style-modern-jazz', 'sous-style-lyrical', 'sous-style-street-jazz', 'sous-style-afro-jazz',
    ],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'jazz',
  },
  {
    numero: 8,
    titre: 'Heels',
    description: 'Danse sur talons hauts : posture, walks, mouvements signature, floorwork, présence et filiations culturelles.',
    coursIds: ['intro-heels'],
    termeIds: [
      'posture-heels', 'walk-heels', 'strut', 'body-roll-heels', 'hair-toss',
      'floorwork-heels', 'frame-heels', 'sass', 'cat-walk-heels', 'vogue-ballroom-heels', 'heel-turn',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'heels',
  },
  {
    numero: 9,
    titre: 'Cabaret',
    description: 'Esthétiques scéniques, french cancan, revue et music-hall, port du costume et des accessoires, lignes de chorus.',
    coursIds: ['intro-cabaret'],
    termeIds: [
      'french-cancan', 'high-kick', 'fan-kick', 'chorus-line', 'synchronisation-chorus',
      'grand-ecart-cancan', 'accroche-pied', 'revue', 'tableau-revue',
      'chahut', 'galop-cancan', 'arabesque-cancan', 'porte-jupon',
      'port-costume', 'canne-chapeau-cabaret', 'boa-eventail',
      'meneuse-revue', 'presentation-scenique', 'rapport-public',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'cabaret',
  },
  {
    numero: 10,
    titre: 'Effeuillage burlesque',
    description: 'Art du dévoilement progressif, jeu de scène, personnage et rapport au public : le vocabulaire du burlesque artistique.',
    coursIds: ['intro-burlesque'],
    termeIds: [
      'effeuillage', 'tease', 'character-burlesque', 'shimmy', 'bump-grind',
      'prop-burlesque', 'timing-burlesque', 'neo-burlesque',
      'fan-dance', 'strut-burlesque', 'pasties', 'nom-scene-burlesque', 'pose-burlesque',
      'glove-peel', 'reveal-burlesque', 'comedy-burlesque', 'tassel-twirling', 'glamour-burlesque',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'burlesque',
  },
  {
    numero: 11,
    titre: 'Pole dance',
    description: "Pole sport, pole art, exotic et pole theatre : prises, montées, figures, inversions, floorwork — et l'histoire de celles qui ont créé cette discipline.",
    coursIds: ['intro-pole-dance', 'histoire-culturelle-pole'],
    termeIds: [
      'grip-pole', 'prise-basique', 'montee-pole', 'spin-pole', 'figure-statique',
      'inversion-pole', 'ayesha', 'floorwork-pole', 'conditioning-pole',
      'pole-sport', 'pole-art', 'exotic-pole', 'origine-pole',
    ],
    quizDisponibles: ['qcm', 'association', 'reconnaissance-visuelle', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'pole-dance',
  },
  {
    numero: 12,
    titre: 'Tango argentin',
    description: "L'abrazo, l'eje, la caminada et les figures improvisées — le vocabulaire du tango argentin social, né dans les faubourgs de Buenos Aires et inscrit au patrimoine de l'UNESCO.",
    coursIds: ['intro-tango-argentin'],
    termeIds: [
      'postura-tango', 'compas-tango', 'transfert-de-poids', 'roles-tango',
      'connexion-tango', 'codigos-milonga', 'vals-tango', 'ronda', 'practica-tango',
      'abrazo', 'eje', 'apilado',
      'cadencia', 'caminada', 'salida-tango', 'paso-lateral', 'cambio-de-peso-en-place',
      'disociacion-tango', 'pivot-tango', 'coleccion-tango',
      'cruce', 'pausa-tango', 'resolucion-tango', 'media-vuelta',
      'ocho', 'parada', 'molinete',
      'adorno-tango', 'amague', 'lapiz',
      'gancho', 'boleo', 'barrida', 'enrosque',
      'sacada', 'volcada', 'colgada',
      'milonga', 'cabeceo', 'tanda', 'musicalidad-tango', 'improvisacion-tango',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'tango-argentin',
  },
  {
    numero: 13,
    titre: 'Danser sans se blesser',
    description: 'Prévention fondée sur la science : épidémiologie, facteurs de risque, renforcement neuromusculaire et spécificités par discipline.',
    coursIds: ['prevention-generale', 'prevention-par-discipline'],
    termeIds: [
      'blessure-surmenage', 'blessure-traumatique', 'facteurs-risque',
      'echauffement-danse', 'retour-au-calme', 'renforcement-neuromusculaire',
      'gainage-fonctionnel', 'souplesse-mobilite', 'repos-recuperation',
      'entorse-cheville', 'tendinopathie', 'syndrome-rotulien',
      'equilibre-musculaire', 'hygiene-vie', 'sante-mentale-danse',
    ],
    quizDisponibles: ['qcm', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'sante',
  },
  {
    numero: 14,
    titre: "L'art de l'improvisation et la composition",
    description: 'Improvisation comme outil de création, composition chorégraphique et une fiche culturelle sur les systèmes de notation de la danse.',
    coursIds: ['improvisation', 'composition', 'notation-danse'],
    termeIds: [
      'improvisation-structuree', 'contrainte-creative', 'donnee-de-depart',
      'etat-de-disponibilite', 'ecoute-partenaire', 'taches-choreographiques',
      'motif-choregraphique', 'phrase-choregraphique', 'procedes-composition',
      'structure-choregraphique', 'intention-artistique',
      'notation-mouvement', 'labanotation', 'benesh-notation', 'video-comme-notation',
    ],
    quizDisponibles: ['qcm', 'association', 'texte-a-trous', 'flashcards'],
    iconeSvgId: 'improvisation',
  },
]
