import type { Terme } from '../schema'

export const termesUnite11: Terme[] = [

  // ─── Improvisation ────────────────────────────────────────────────────────

  {
    id: 'improvisation-structuree',
    nom: 'Improvisation structurée',
    alias: ['improvisation contrainte', 'improvisation guidée', 'structured improvisation', 'improvisation avec score'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique', 'pole-dance', 'burlesque'],
    categories: ['concepts'],
    definition: "Forme d'improvisation encadrée par des règles, des contraintes ou un score ouvert — par opposition à l'improvisation totalement libre. La structure libère en réduisant le champ des possibles à un espace explorable.",
    description: "L'improvisation 'pure' (sans aucune contrainte) est souvent paralysante. La paradoxe de l'improvisation : *plus le cadre est précis, plus l'artiste est libre à l'intérieur de ce cadre.*\n\n**Types de structures :**\n\n**Score ouvert :** Partition avec des paramètres définis mais pas de résultat fixé. Ex : 'Traverse l'espace en changeant de niveau chaque fois que tu croises quelqu'un.'\n\n**Tâche chorégraphique :** Consigne précise qui génère du mouvement. Ex : 'Explore toutes les façons de passer d'une chaise à une autre sans toucher le sol.'\n\n**Contrainte formelle :** Limitation qui force la créativité. Ex : 'Tu ne peux utiliser que le plan sagittal' ou 'chaque phrase doit durer exactement 8 temps.'\n\n**Score de relation :** Structure qui définit comment les danseurs interagissent. Ex : 'Un leader, un suiveur — changement de rôle au signal.'\n\n**Pourquoi l'improvisation structurée est un outil pédagogique :**\nElle permet d'explorer du matériel chorégraphique qu'on n'aurait jamais trouvé par composition consciente — le corps sait des choses que l'esprit n'a pas encore formulées.",
    erreursCourantes: [
      "Confondre improvisation et manque de préparation — l'improvisation de qualité demande des heures de pratique et de développement.",
      "Arrêter de bouger quand on 'ne sait plus quoi faire' — la panne est de l'information, pas un échec.",
    ],
    conseils: [
      "En improvisation, il n'y a pas de 'mauvais choix' — il y a des choix plus ou moins assumés. Aller jusqu'au bout de chaque impulse.",
    ],
    etymologie: "Du latin *improvisus* (*im-* privatif + *provisus*, participe de *providere* : voir à l'avance, prévoir). Improviser c'est agir sans avoir vu à l'avance. Le paradoxe du terme : la structure (ce qui est prévu) encadre l'improvisation (ce qui ne l'est pas) pour lui donner un espace vivable.",
    difficulteInterne: 2,
    termesLies: ['contrainte-creative', 'donnee-de-depart', 'instant-composition'],
  },

  {
    id: 'contrainte-creative',
    nom: 'Contrainte créative',
    alias: ['creative constraint', 'cadre créatif', 'limitation productive'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique', 'heels', 'pole-dance', 'burlesque', 'cabaret'],
    categories: ['concepts'],
    definition: "Règle ou limitation volontairement imposée au processus créatif pour en stimuler l'inventivité — le cadre paradoxalement libérateur.",
    description: "Le principe est issu de l'Oulipo en littérature (écrire sans la lettre 'e', etc.) et s'applique directement à la danse.\n\n**Pourquoi les contraintes sont créatives :**\nFace à l'infini des possibles, le cerveau se bloque. Face à une contrainte, il trouve des solutions inattendues.\n\n**Types de contraintes en danse :**\n\n**Contraintes de corps :**\n- 'N'utilise qu'une seule partie du corps'\n- 'Une articulation doit toujours être en contact avec le sol'\n- 'Tes yeux ne quittent jamais un point fixe'\n\n**Contraintes d'espace :**\n- 'Tu ne peux te déplacer qu'en ligne droite'\n- 'Reste dans un cercle de 2 mètres'\n- 'Utilise uniquement les coins de la salle'\n\n**Contraintes de temps :**\n- 'Toutes tes phrases durent exactement 5 secondes'\n- 'Tu es en slow motion pendant 2 minutes'\n- 'Chaque mouvement dure deux fois plus longtemps que tu ne le prévois'\n\n**Contraintes de relation :**\n- 'Toujours face à un autre danseur'\n- 'Ne jamais être à moins de 3 mètres de quelqu'un'\n- 'Miroir permanent'\n\n**La contrainte comme outil chorégraphique :**\nBeaucoup de pièces contemporaines naissent d'une contrainte de départ — Trisha Brown, Pina Bausch, Anne Teresa De Keersmaeker ont toutes utilisé des systèmes de contraintes pour générer du matériel.",
    erreursCourantes: [],
    etymologie: "Du latin *contrahere* (serrer, lier) → *contractus*. La contrainte est ce qui lie, ce qui serre — mais en créant une pression, elle force l'énergie à trouver un autre chemin. Le paradoxe est au cœur du terme : ce qui comprime libère.",
    difficulteInterne: 1,
    termesLies: ['improvisation-structuree', 'taches-choreographiques', 'motif-choregraphique'],
  },

  {
    id: 'donnee-de-depart',
    nom: 'Donnée de départ',
    alias: ['impulse de départ', 'starting point', 'point de départ créatif', 'prompt chorégraphique'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique', 'burlesque'],
    categories: ['concepts'],
    definition: "Élément initial — image, sensation, son, concept, texte, objet ou contrainte — qui déclenche et oriente un processus d'improvisation ou de composition chorégraphique.",
    description: "La donnée de départ est l'étincelle du processus créatif. Tout chorégraphe, tout improvisateur en a besoin — l'art est de la choisir et de la laisser guider sans l'étouffer.\n\n**Types de données de départ :**\n\n**Kinesthésique :** Une qualité de mouvement, une sensation physique, un poids.\nEx : 'Commence par sentir le poids de tes bras'\n\n**Sonore :** Un son, un rythme, une musique, un silence.\nEx : 'Réponds physiquement à chaque son dans l'espace'\n\n**Visuelle :** Une image, une couleur, une forme.\nEx : 'Tu es une marionnette dont on coupe progressivement les fils'\n\n**Conceptuelle :** Une idée, une émotion, une question.\nEx : 'Qu'est-ce que la résistance dans le corps ?'\n\n**Textuelle :** Un poème, un mot, une phrase.\nEx : 'Incarne chaque mot de cette liste : tomber, flotter, percuter, fondre'\n\n**Relationnelle :** L'autre, l'espace, un objet.\nEx : 'Comment s'adapter au mouvement de l'autre sans jamais l'imiter ?'\n\n**Comment travailler avec une donnée de départ :**\n1. La recevoir — la laisser résonner avant de bouger\n2. La laisser guider les premières impulsions\n3. La développer — où ça mène ?\n4. La transformer — que se passe-t-il si on la pousse à l'extrême ?\n5. La quitter — quand elle a rempli sa fonction",
    erreursCourantes: [],
    difficulteInterne: 1,
    termesLies: ['improvisation-structuree', 'contrainte-creative', 'etat-de-disponibilite'],
  },

  {
    id: 'etat-de-disponibilite',
    nom: "État de disponibilité",
    alias: ['readiness', 'état ouvert', 'présence totale', 'neutral state', 'état neutre'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique', 'burlesque', 'cabaret'],
    categories: ['concepts'],
    definition: "État corporel et mental de pleine réceptivité — ni passif ni hyper-actif — qui permet de percevoir, répondre et agir avec spontanéité dans l'instant présent.",
    description: "L'état de disponibilité est la condition préalable à toute improvisation de qualité. Sans lui, le danseur exécute des habitudes au lieu de répondre à ce qui se passe.\n\n**Ce que n'est pas l'état de disponibilité :**\n- La relaxation totale (passivité)\n- La tension maximale (rigidité)\n- La liste d'intentions préparées à l'avance\n\n**Ce qu'il est :**\n- Tonus équilibré — corps prêt mais non contracté\n- Attention diffuse — percevoir l'espace entier, pas un point précis\n- Suspension du jugement — ni 'c'est bon' ni 'c'est nul'\n- Présence au moment — ni dans le souvenir de ce qui vient de se passer, ni dans l'anticipation\n\n**Comment cultiver l'état de disponibilité :**\n\n**Pratiques préparatoires :**\n- Scan corporel lent (sentir chaque partie du corps)\n- Marche neutre dans l'espace, sans destination\n- Regard périphérique (élargir la vision)\n- Respiration abdominale profonde\n\n**Le 'comme si' de Stanislavski appliqué à la danse :**\nL'état de disponibilité est le 'comme si je ne savais pas ce qui va arriver' — même dans une pièce répétée, trouver la fraîcheur du premier regard.",
    erreursCourantes: [],
    difficulteInterne: 2,
    termesLies: ['donnee-de-depart', 'ecoute-partenaire', 'improvisation-structuree'],
  },

  {
    id: 'ecoute-partenaire',
    nom: 'Écoute du partenaire',
    alias: ['kinesthetic listening', 'écoute kinesthésique', 'réponse à l\'autre', 'dialogue corporel'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique', 'pole-dance'],
    categories: ['concepts'],
    definition: "Capacité à percevoir et répondre au mouvement, au poids et aux intentions d'un partenaire de danse — à travers le toucher en contact improvisation, ou à travers la vision et la perception de l'espace partagé.",
    description: "L'écoute du partenaire est une compétence distincte de l'écoute musicale ou de la mémorisation — c'est la capacité à être en dialogue réel, pas en monologue simultané.\n\n**Les deux modes d'écoute :**\n\n**Écoute tactile (contact improvisation) :**\nLire les intentions et le poids de l'autre à travers le point de contact physique. C'est une conversation en temps réel — aucun partenaire ne 'mène' unilatéralement.\n\n**Écoute visuelle et spatiale :**\nPercevoir les qualités de mouvement, les dynamiques, les directions de l'autre à distance. Répondre sans copier.\n\n**Les niveaux de réponse :**\n\n1. **Miroir** — imiter (point de départ, mais pas une fin)\n2. **Écho** — reprendre avec décalage ou variation\n3. **Contraste** — répondre par l'opposé\n4. **Complétion** — terminer ce que l'autre a commencé\n5. **Ignorance active** — ne pas répondre (choix intentionnel)\n\n**Les pièges :**\n- Anticiper au lieu d'écouter (préparer sa réponse avant d'avoir reçu la proposition)\n- Écouter uniquement ce qu'on veut entendre\n- Dominer (imposer sa direction sans laisser l'autre répondre)\n\n**Exercices de base :**\n- Mirroring progressif (de lent à rapide, face à face)\n- 'Oui, et...' du théâtre d'improvisation appliqué au mouvement\n- Suivi du centre de masse en contact",
    erreursCourantes: [],
    difficulteInterne: 2,
    termesLies: ['etat-de-disponibilite', 'improvisation-structuree', 'point-de-contact'],
  },

  {
    id: 'taches-choreographiques',
    nom: 'Tâches chorégraphiques',
    alias: ['movement tasks', 'tâches de mouvement', 'tasks', 'consignes de mouvement'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique'],
    categories: ['concepts'],
    definition: "Consignes ou problèmes de mouvement concrets posés aux danseurs pour générer du matériel chorégraphique — méthode pédagogique et créative issue de la danse postmoderne américaine.",
    description: "Les tâches chorégraphiques ont été développées comme méthode par des chorégraphes comme Trisha Brown, Yvonne Rainer et le Judson Dance Theater dans les années 1960.\n\n**Le principe :** Poser un problème de mouvement plutôt qu'enseigner un mouvement. La solution appartient au corps du danseur.\n\n**Exemples de tâches :**\n\n**Tâches d'exploration :**\n- 'Trouve 10 façons différentes de tomber'\n- 'Explore tous les niveaux de l'espace en 2 minutes'\n- 'Marche de A à B en changeant la qualité de mouvement tous les 10 secondes'\n\n**Tâches de relation :**\n- 'Reste toujours à égale distance de deux autres personnes'\n- 'Ne regarde jamais dans la direction où tu vas'\n\n**Tâches d'attention :**\n- 'Observe un détail architectural et laisse-le influencer ton mouvement'\n- 'Danse comme si le plafond pesait 10 kilos'\n\n**Tâches de transformation :**\n- 'Prends un geste quotidien et agrandis-le x100'\n- 'Danse le même trajet mais dans des qualités opposées'\n\n**Utilisation pédagogique :**\nLes tâches permettent à chaque danseur de trouver son propre mouvement — le résultat est plus riche et plus personnel qu'une technique transmise.",
    erreursCourantes: [],
    difficulteInterne: 1,
    termesLies: ['contrainte-creative', 'improvisation-structuree', 'motif-choregraphique'],
  },

  // ─── Composition chorégraphique ──────────────────────────────────────────

  {
    id: 'motif-choregraphique',
    nom: 'Motif chorégraphique',
    alias: ['motif de mouvement', 'movement motif', 'cellule chorégraphique', 'phrase germe'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique'],
    categories: ['concepts'],
    definition: "Unité minimale de sens chorégraphique — une courte séquence de mouvement reconnaissable qui peut être répétée, variée et développée pour construire une composition.",
    description: "Le motif est l'équivalent chorégraphique du thème musical. Comme un thème en musique peut structurer toute une symphonie, un motif de mouvement peut construire toute une pièce.\n\n**Caractéristiques d'un bon motif :**\n- Mémorable (reconnaissable quand il revient)\n- Riche (assez complexe pour être varié)\n- Concis (assez court pour être répété)\n- Expressif (porteur de sens ou de qualité)\n\n**Les opérations sur le motif (procédés de composition) :**\n\n**Répétition :** Le motif revient identique — insistance, rituel.\n\n**Variation :** Le motif change en préservant son identité — même dessin, qualité différente ; même qualité, espace différent.\n\n**Développement :** Le motif est amplifié, étiré, fragmenté.\n\n**Fragmentation :** On ne garde qu'une partie du motif.\n\n**Superposition :** Deux motifs simultanés (canon, contrepoint).\n\n**Inversion :** Le motif à l'envers dans le temps (retrograde) ou dans l'espace (symétrie).\n\n**Augmentation / Diminution :** Le motif en lent motion ou accéléré.\n\n**Comment trouver un motif :**\nSouvent à partir d'une improvisation — identifier le moment où quelque chose d'intéressant se produit, l'isoler, l'apprendre, le répéter.",
    erreursCourantes: [],
    etymologie: "Du latin *motivus* (qui met en mouvement), de *movere* (bouger, émouvoir). Un motif est ce qui *meut* — en musique comme en danse, c'est la cellule minimale qui contient assez d'énergie pour générer tout le reste.",
    difficulteInterne: 2,
    termesLies: ['procedes-composition', 'structure-choregraphique', 'phrase-choregraphique'],
  },

  {
    id: 'phrase-choregraphique',
    nom: 'Phrase chorégraphique',
    alias: ['phrase de mouvement', 'movement phrase', 'séquence chorégraphique'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique'],
    categories: ['concepts'],
    definition: "Séquence de mouvements ayant un début, un développement et une fin — unité de sens chorégraphique plus longue qu'un motif, analogue à la phrase musicale ou grammaticale.",
    description: "La phrase chorégraphique est l'unité de base du vocabulaire d'une pièce. Comme une phrase en langage, elle a une structure interne : impulsion initiale, développement, résolution.\n\n**Anatomie d'une phrase :**\n\n**L'impulsion (anacrusse) :** Le mouvement initial qui lance la phrase — souvent sur le temps fort ou avant lui.\n\n**Le développement :** Le corps de la phrase — où va l'énergie, comment elle se transforme.\n\n**La résolution :** La fin de la phrase — l'énergie trouve son terme ou se suspend.\n\n**Qualification des phrases :**\n- **Phrase ouverte** : se termine sur une suspension, appelle la suite\n- **Phrase fermée** : se termine sur une résolution complète\n- **Phrase cyclique** : sa fin est en même temps son début\n\n**La phrase en danseur :**\nConnaître une phrase veut dire pouvoir la démarrer à n'importe quel moment, la moduler selon le contexte musical et spatial, et la transmettre à quelqu'un d'autre.\n\n**Différence phrase / motif :**\nLe motif est la cellule germe (3–8 temps en général). La phrase est l'unité complète (8–32 temps selon le style). Une phrase contient souvent plusieurs motifs.",
    erreursCourantes: [],
    etymologie: "Du grec *phrasis* (façon de parler, expression, locution), de *phrazein* (parler, exprimer). Emprunté à la linguistique et à la musique : une phrase a une unité de sens, un début et une fin. La danse l'a adopté pour nommer la même unité dans le mouvement.",
    difficulteInterne: 1,
    termesLies: ['motif-choregraphique', 'structure-choregraphique', 'procedes-composition'],
  },

  {
    id: 'procedes-composition',
    nom: 'Procédés de composition',
    alias: ['compositional devices', 'outils de composition', 'techniques chorégraphiques', 'procédés chorégraphiques'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique'],
    categories: ['concepts'],
    definition: "Ensemble des opérations formelles qu'un chorégraphe peut appliquer à un matériau de mouvement pour le transformer, le développer et structurer une pièce.",
    description: "Les procédés de composition sont les outils du chorégraphe — comme les opérations mathématiques sont les outils du mathématicien. Les maîtriser permet de transformer n'importe quel matériau brut en composition élaborée.\n\n**Les procédés fondamentaux :**\n\n**Répétition :** Revenir à un matériau identique. Crée la reconnaissance et l'insistance.\n\n**Rétrograde :** Exécuter une phrase à l'envers dans le temps. Crée un sentiment d'étrangeté familière.\n\n**Inversion :** Retourner une phrase dans l'espace (haut/bas, gauche/droite). Miroir.\n\n**Canon :** Le même matériau exécuté en décalage temporel par plusieurs danseurs. La fugue du mouvement.\n\n**Unisson :** Tous ensemble, en même temps. Puissance du collectif.\n\n**Accumulation :** Ajouter progressivement des éléments (Trisha Brown : 1, 1+2, 1+2+3...)\n\n**Fragmentation :** Extraire un élément d'une phrase et l'isoler.\n\n**Transposition :** La même phrase dans un niveau différent (au sol, debout, en saut).\n\n**Augmentation / Diminution :** Ralentir ou accélérer le rythme d'une phrase.\n\n**Combinaison :** Jouer plusieurs procédés simultanément (canon + inversion, par exemple).\n\n**Anne Teresa De Keersmaeker (Fase, 1982) :**\nL'exemple ultime de composition par procédés — deux danseuses en canon, répétition, rotation progressive dans l'espace, développée sur 60 minutes.",
    erreursCourantes: [],
    etymologie: "Du latin *compositus*, participe de *componere* (com- + ponere : mettre ensemble, assembler). Composer, c'est assembler des éléments épars en un tout. Le terme est partagé avec la musique, l'architecture et la peinture — arts qui tous assemblent des parties pour former une unité.",
    difficulteInterne: 3,
    termesLies: ['motif-choregraphique', 'structure-choregraphique', 'canon'],
  },

  {
    id: 'structure-choregraphique',
    nom: 'Structure chorégraphique',
    alias: ['forme chorégraphique', 'choreographic structure', 'forme de la pièce', 'architecture chorégraphique'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique', 'burlesque', 'cabaret'],
    categories: ['concepts'],
    definition: "Organisation globale d'une pièce de danse dans le temps — la façon dont les différentes sections, matériaux et moments s'articulent pour former un tout cohérent.",
    description: "La structure chorégraphique est l'architecture de la pièce. Comme un bâtiment a un plan, une pièce de danse a une forme — même si cette forme peut être très ouverte.\n\n**Formes structurelles classiques :**\n\n**AB (Binaire) :** Deux sections contrastées. Simple et efficace pour un solo ou un duo.\n\n**ABA (Ternaire) :** Introduction d'un thème, contraste, retour. Le modèle de la sonate, très utilisé en danse aussi.\n\n**Rondo (ABACAD...) :** Un thème principal qui revient, entrecoupé de digressions. Dynamique et narratif.\n\n**Through-composed :** Développement continu sans retour — une transformation permanente du début à la fin.\n\n**Suite :** Succession de sections indépendantes avec une logique commune.\n\n**Arch (ABCBA) :** Structure symétrique autour d'un point central.\n\n**Structure narrative :** Introduction → nœud → développement → climax → résolution. Structure du récit.\n\n**Questions que pose la structure :**\n- Comment commence la pièce ? (In medias res ou introduction progressive ?)\n- Où est le climax ? (Début, milieu, fin ?)\n- Comment finit la pièce ? (Résolution, suspension, effacement ?)\n- Quelle est la durée idéale ? (Toujours plus court qu'on ne pense)\n- Y a-t-il une transformation du matériau entre le début et la fin ?",
    erreursCourantes: [],
    etymologie: "Du latin *structura* (assemblage, construction, liaison), de *struere* (bâtir, empiler, ordonner). La structure chorégraphique est l'architecture invisible de la pièce — l'ordre dans lequel les briques sont posées pour que l'édifice tienne.",
    difficulteInterne: 2,
    termesLies: ['motif-choregraphique', 'procedes-composition', 'intention-artistique'],
  },

  {
    id: 'intention-artistique',
    nom: 'Intention artistique',
    alias: ['intention chorégraphique', 'propos artistique', 'statement artistique', 'vision chorégraphique'],
    disciplines: ['contemporain', 'moderne', 'jazz', 'classique', 'burlesque', 'cabaret', 'pole-dance'],
    categories: ['concepts'],
    definition: "Ce que l'artiste veut dire, explorer ou provoquer avec une pièce — la question, l'émotion, l'idée ou la sensation que la composition cherche à transmettre ou à générer.",
    description: "L'intention artistique n'est pas un message illustratif ('cette pièce parle de la guerre') — c'est un désir de partager une expérience, une question, une qualité de présence.\n\n**La différence entre sujet et intention :**\n- **Sujet** : 'Cette pièce parle de la mémoire' (descriptif)\n- **Intention** : 'Je veux que le public ressente la dissolution progressive de ce qu'on croit se rappeler' (expérientiel)\n\n**Comment articuler son intention :**\n'Je veux que le spectateur [verbe d'expérience] [quelque chose] [en rapport avec la matière].'\nEx : 'Je veux que le spectateur *éprouve* le vertige du temps qui s'accélère sans qu'on puisse le saisir.'\n\n**L'intention guide les choix :**\nTout choix chorégraphique — musique, lumière, costume, structure, interprètes — devrait être éclairé par l'intention.\n\n**Note-d'intention vs pièce :**\nL'intention n'est pas dans le programme — elle est dans le corps. Si tu dois l'expliquer après la pièce, c'est qu'elle n'était pas dans la danse.\n\n**L'intention comme boussole, pas comme cage :**\nL'intention peut évoluer pendant le processus créatif. Un bon chorégraphe écoute ce que la pièce veut devenir — pas seulement ce qu'il voulait faire au départ.",
    erreursCourantes: [],
    difficulteInterne: 2,
    termesLies: ['structure-choregraphique', 'motif-choregraphique', 'donnee-de-depart'],
  },

  // ─── Notation de la danse ─────────────────────────────────────────────────

  {
    id: 'notation-mouvement',
    nom: 'Notation du mouvement',
    alias: ['dance notation', 'écriture du mouvement', 'notation de la danse', 'partition de danse'],
    disciplines: ['classique', 'contemporain', 'moderne', 'jazz'],
    categories: ['culture-histoire'],
    definition: "Ensemble des systèmes graphiques développés pour transcrire le mouvement humain sur papier — permettre la conservation, la transmission et l'analyse des œuvres chorégraphiques.",
    description: "La danse a longtemps été une art de transmission orale — maître à élève, corps à corps. La notation vise à créer un équivalent de la partition musicale pour le mouvement.\n\n**Le problème fondamental :**\nLe mouvement est quadridimensionnel (x, y, z + temps), continu, et concerne simultanément la position, la qualité, le rythme, l'espace et la relation. Le noter est infiniment plus complexe que noter une mélodie.\n\n**Les principaux systèmes :**\n\n**Labanotation (1928) :** Créée par Rudolf Laban — colonnes verticales représentant les parties du corps, symboles pour direction et niveau. Le système le plus utilisé en Europe et Amérique du Nord.\n\n**Notation Benesh (1955) :** Créée par Joan et Rudolf Benesh — portée horizontale à 5 lignes représentant le corps (tête en haut, pieds en bas). Utilisée au Royal Ballet et dans le ballet classique britannique.\n\n**Eshkol-Wachman (1958) :** Système mathématique basé sur les angles et les coordonnées sphériques. Très précis, utilisé en recherche.\n\n**Motus Humanus :** Système plus récent intégrant les qualités de mouvement.\n\n**La vidéo comme complément :**\nAujourd'hui, la plupart des compagnies utilisent la vidéo pour archiver — plus rapide, moins précis pour certains paramètres (qualité de mouvement difficile à lire sur vidéo). La notation et la vidéo sont complémentaires.",
    erreursCourantes: [],
    etymologie: "Du latin *nota* (signe, marque, lettre) et *movere* (bouvoir). 'Noter le mouvement' — noter ce qui ne reste pas. La tension est dans les mots mêmes : la notation est fixe, le mouvement est fugace. Toute l'histoire de la notation du mouvement est une tentative de résoudre ce paradoxe.",
    difficulteInterne: 2,
    termesLies: ['labanotation', 'benesh-notation', 'video-comme-notation'],
  },

  {
    id: 'labanotation',
    nom: 'Labanotation',
    alias: ['kinetographie Laban', 'Laban Movement Notation', 'notation Laban'],
    disciplines: ['classique', 'contemporain', 'moderne', 'jazz'],
    categories: ['culture-histoire'],
    definition: "Système de notation chorégraphique créé par Rudolf Laban en 1928 — le plus utilisé dans le monde pour la transcription formelle des œuvres de danse.",
    description: "Rudolf Laban (1879–1958) a développé un système complet d'analyse et de notation du mouvement — dont la Labanotation est la branche de transcription écrite.\n\n**Principe de lecture :**\nLa partition se lit de bas en haut (comme le temps qui monte). Elle est divisée en colonnes verticales représentant chaque partie du corps.\n\n**Les éléments de base :**\n- **Symboles directionnels** : Indiquent la direction du mouvement (8 directions + niveau bas/milieu/haut)\n- **Durée** : La longueur du symbole indique la durée (long = lent, court = rapide)\n- **Pied support** : Colonnes centrales pour la jambe d'appui\n- **Gestuels** : Colonnes pour les bras, la tête, le torse\n\n**Ce que la Labanotation peut noter :**\n- Direction précise de chaque mouvement\n- Niveau (haut, milieu, bas)\n- Timing et rythme\n- Partie du corps impliquée\n- Rotation, accent\n\n**Ce qu'elle note moins facilement :**\n- Les qualités de mouvement (effort Laban) — notées séparément\n- L'expression, l'intention\n- Les contacts entre danseurs\n\n**Où l'apprendre :**\nL'Institut Laban propose des formations — la maîtrise complète de la Labanotation demande plusieurs années.",
    erreursCourantes: [],
    etymologie: "Contraction de 'Laban notation' — du nom de Rudolf von Laban (1879–1958), son créateur, et de 'notation' (latin *nota*, signe, marque). Le système Laban permet d'écrire le mouvement comme on écrit la musique — une ambition révolutionnaire pour l'époque.",
    difficulteInterne: 3,
    termesLies: ['notation-mouvement', 'benesh-notation', 'effort-laban'],
  },

  {
    id: 'benesh-notation',
    nom: 'Notation Benesh',
    alias: ['Benesh Movement Notation', 'BMN', 'choreology'],
    disciplines: ['classique', 'contemporain'],
    categories: ['culture-histoire'],
    definition: "Système de notation chorégraphique créé par Joan et Rudolf Benesh en 1955 — utilisé principalement dans le monde du ballet classique, notamment au Royal Ballet de Londres.",
    description: "Joan Benesh (1920–2008), danseuse du Royal Ballet, et Rudolf Benesh (1916–1975), mathématicien, ont développé un système intuitif pour les danseurs formés en musique.\n\n**Principe de lecture :**\nLa notation Benesh utilise une portée à **5 lignes horizontales** représentant le corps humain vu de dos :\n- Ligne supérieure : sommet de la tête\n- 2e ligne : épaules\n- 3e ligne : taille\n- 4e ligne : genoux\n- Ligne inférieure : sol\n\n**Les symboles :**\n- **Points et tirets** sur et entre les lignes pour la position des mains et pieds\n- **Signes de croissement** pour indiquer les parties du corps devant/derrière\n- **Symboles de mouvement** pour les déplacements et les rotations\n\n**Avantages :**\n- Lisible sur une portée musicale (en-dessous de la musique)\n- Intuitif pour les musiciens-danseurs\n- Précis pour le ballet classique\n\n**Utilisation actuelle :**\nLe Royal Ballet, l'English National Ballet et plusieurs compagnies internationales utilisent la notation Benesh pour archiver leur répertoire. Les notateurs Benesh sont des spécialistes reconnus dans ces institutions.",
    erreursCourantes: [],
    etymologie: "Contraction des noms de Joan (1920–2008) et Rudolf (1916–1975) Benesh, ses créateurs. Joan Benesh, danseuse du Royal Ballet, et son mari Rudolf, mathématicien, ont mis en commun leurs deux langages — celui du corps et celui des nombres — pour inventer un système hybride.",
    difficulteInterne: 3,
    termesLies: ['notation-mouvement', 'labanotation', 'video-comme-notation'],
  },

  {
    id: 'video-comme-notation',
    nom: 'Vidéo comme outil de notation',
    alias: ['video notation', 'vidéo archive', 'captation chorégraphique', 'documentation vidéo'],
    disciplines: ['classique', 'contemporain', 'moderne', 'jazz', 'heels', 'pole-dance', 'burlesque'],
    categories: ['culture-histoire'],
    definition: "Utilisation de l'enregistrement vidéo comme moyen de préserver et transmettre une œuvre chorégraphique — méthode dominante dans la pratique actuelle, complémentaire aux systèmes de notation formelle.",
    description: "La démocratisation de la vidéo (VHS dans les années 1980, puis numérique) a profondément transformé la façon dont la danse est archivée et transmise.\n\n**Avantages de la vidéo :**\n- Accessibilité (tout le monde peut filmer et regarder)\n- Fidélité visuelle (on voit vraiment ce qui se passe)\n- Vitesse (filmer est infiniment plus rapide qu'écrire en notation)\n- Capture les détails expressifs et qualitatifs\n- Montre l'interprète réel (pas une abstraction)\n\n**Limites de la vidéo :**\n- Dépend du point de vue de la caméra (ce qui n'est pas filmé n'existe pas)\n- Difficile de lire certains paramètres spatiaux (distances, trajectoires au sol)\n- Ne transcrit pas facilement les qualités de mouvement en instructions\n- Nécessite de voir l'ensemble du corps simultanément → multicaméras\n- Formats qui deviennent obsolètes (VHS, DVD...)\n\n**Bonnes pratiques de captation chorégraphique :**\n- Filmer depuis plusieurs angles\n- Captation de face + de côté\n- Inclure une prise avec annotations orales\n- Conserver les fichiers en haute qualité sur plusieurs supports\n\n**La vidéo et la transmission :**\nMême avec une vidéo parfaite, recréer une pièce demande un passeur humain — quelqu'un qui connaît la pièce de l'intérieur. La vidéo montre *quoi*, pas *comment* ni *pourquoi*.",
    erreursCourantes: [],
    difficulteInterne: 1,
    termesLies: ['notation-mouvement', 'labanotation', 'benesh-notation'],
  },
]
